# Generated by Django 5.2.1 on 2025-08-26 10:06

from django.db import migrations

from maykin_common.migration_operations import ResetSequences


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        ResetSequences(),
    ]
